@startuml TelemetryService_Component
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(telemetryService, "Telemetry Service", "Django")

Component(api, "TelemetryGrpcEndpoint", "gRPC Endpoint", "Предоставление телеметрии по запросу")
Component(collector, "TelemetryCollector", "Service", "Получение телеметрии от устройств")
Component(repo, "TelemetryRepository", "Repository", "Хранение данных телеметрии")
Component(eventPublisher, "TelemetryEventProducer", "Kafka Producer", "Публикация событий об изменениях")

Rel(api, repo, "Чтение данных")
Rel(collector, repo, "Сохраняет телеметрию")
Rel(collector, eventPublisher, "Публикует в Kafka")

@enduml